### ISSUE TITLE
Low-light enhancement and

### ISSUE THREAD

**Issue by Lz-2019317** [pminhtam/MIRnet_SIDD#1]

**Comment by Lz-2019317** [comment]
Thank you open your training code about MIRNet, Does this code also work for low light enhancement tasks?

**Comment by pminhtam** [comment]
> Thank you open your training code about MIRNet, Does this code also work for low light enhancement tasks?

Yes, this task uses the same model with denoising.

**Comment by Lz-2019317** [comment]
Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pminhtam/MIRnet_SIDD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pminhtam/MIRnet_SIDD] Low-light enhancement and (Issue #1)





  
Thank you open your training code about MIRNet, Does this code also work for low light enhancement tasks?
  
Yes, this task uses the same model with denoising.
